/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter2: typeof import('./components/AppFooter2.vue')['default']
    AppNav: typeof import('./components/AppNav.vue')['default']
    CoverflowSlider2: typeof import('./components/CoverflowSlider2.vue')['default']
    HowItWorks: typeof import('./components/HowItWorks.vue')['default']
    ImageComparisonSlider: typeof import('./components/ImageComparisonSlider.vue')['default']
    ImageContainer: typeof import('./components/imageContainer.vue')['default']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Transform: typeof import('./components/Transform.vue')['default']
  }
}
