/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/A2generate': RouteRecordInfo<'/A2generate', '/A2generate', Record<never, never>, Record<never, never>>,
    '/gallery': RouteRecordInfo<'/gallery', '/gallery', Record<never, never>, Record<never, never>>,
    '/generate': RouteRecordInfo<'/generate', '/generate', Record<never, never>, Record<never, never>>,
    '/landing3': RouteRecordInfo<'/landing3', '/landing3', Record<never, never>, Record<never, never>>,
    '/ProductViewer': RouteRecordInfo<'/ProductViewer', '/ProductViewer', Record<never, never>, Record<never, never>>,
    '/ProductViewerz': RouteRecordInfo<'/ProductViewerz', '/ProductViewerz', Record<never, never>, Record<never, never>>,
  }
}
